[project]
name = "dothe2"
version = "0.1.0"
description = "Yet another To-do web app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "ruff>=0.11.9",
]
